name: Feature
description: Nueva funcionalidad
labels: ["feature"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
    validations:
      required: true
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceptación
      placeholder: "- [ ] ..."
    validations:
      required: true
